tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "hudochenkov/sshpass"
tap "koekeishiya/formulae"
tap "planetscale/tap"
tap "romkatv/powerlevel10k"
brew "gcc"
brew "btop"
brew "cocoapods"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "lua"
brew "mas"
brew "mysql-client"
brew "neofetch"
brew "neovim"
brew "node"
brew "nvm"
brew "pnpm"
brew "rbenv"
brew "ripgrep"
brew "rtorrent"
brew "rust"
brew "tldr"
brew "tmux"
brew "tree"
brew "typescript"
brew "watchman"
brew "weechat"
brew "yarn"
brew "hudochenkov/sshpass/sshpass"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
brew "planetscale/tap/pscale"
brew "romkatv/powerlevel10k/powerlevel10k"
cask "android-studio"
cask "arc"
cask "balenaetcher"
cask "betterdisplay"
cask "discord"
cask "docker"
cask "figma"
cask "font-hack-nerd-font"
cask "gifox"
cask "google-drive"
cask "hammerspoon"
cask "handbrake"
cask "hiddenbar"
cask "iterm2"
cask "linear-linear"
cask "logi-options-plus"
cask "losslesscut"
cask "maxon"
cask "messenger"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "postman"
cask "protonmail-bridge"
cask "protonvpn"
cask "qmk-toolbox"
cask "raycast"
cask "selfcontrol"
cask "slack"
cask "spotify"
cask "stats"
cask "topnotch"
cask "utm"
cask "via"
cask "vial"
cask "visual-studio-code"
cask "wechat"
cask "zoom"
mas "CapCut", id: 1500855883
mas "Developer", id: 640199958
mas "Final Cut Pro", id: 424389933
mas "Logic Pro", id: 634148309
mas "Motion", id: 434290957
mas "Swiftify for Xcode", id: 1183412116
mas "TestFlight", id: 899247664
vscode "GitHub.copilot"
vscode "tomoki1207.pdf"
vscode "vscodevim.vim"
