#!/bin/zsh

# Installation introduction
printf '\033[36m
██████╗  █████╗ ███╗   ██╗██████╗  ██████╗ ██╗  ██╗███████╗     
██╔══██╗██╔══██╗████╗  ██║██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝     
██████╔╝███████║██╔██╗ ██║██║  ██║██║   ██║█████╔╝ ███████╗     
██╔═══╝ ██╔══██║██║╚██╗██║██║  ██║██║   ██║██╔═██╗ ╚════██║     
██║     ██║  ██║██║ ╚████║██████╔╝╚██████╔╝██║  ██╗███████║     
╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝     
                                                                
   ██████╗  ██████╗ ████████╗███████╗██╗██╗     ███████╗███████╗
   ██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝██║██║     ██╔════╝██╔════╝
   ██║  ██║██║   ██║   ██║   █████╗  ██║██║     █████╗  ███████╗
   ██║  ██║██║   ██║   ██║   ██╔══╝  ██║██║     ██╔══╝  ╚════██║
██╗██████╔╝╚██████╔╝   ██║   ██║     ██║███████╗███████╗███████║
╚═╝╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝\033[0m
[\033[35mpress any to continue\033[0m]'
read

# Install Oh My Zsh
printf "Install \033[33mOh My Zsh\033[0m? [\033[35my/n\033[0m] "
read omz
if [[ $omz == "y" || $omz == "Y" ]]; then
  (sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended)
  source ~/.zshrc
  printf "\033[32mSuccessful install\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Install Homebrew and packages
printf "Install \033[33mHomebrew\033[0m? [\033[35my/n\033[0m] "
read brew
if [[ $brew == "y" || $brew == "Y" ]]; then
  printf "\033[31mWarning\033[0m: make sure you are logged in to your Apple ID [\033[35mpress any to continue\033[0m]"
  read
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  printf "\033[33mNote:\033[0m Having a warning in the installation is normal\n"
  printf "Are you on an ARM system? [\033[35my/n\033[0m] "
  read arm
  if [[ $arm == "y" || $arm == "Y" ]]; then
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ./.zprofile
  else
    echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ./.zprofile
  fi
  cp ./.zprofile ~/.zprofile
  source ~/.zprofile
  printf "\033[32mSuccessful install\033[0m\n"
  printf "Install \033[33mBrewfile software packages\033[0m? [\033[35my/n\033[0m] "
  read packages
  if [[ $packages == "y" || $package == "Y" ]]; then
    brew bundle --file=./Brewfile
    source ~/.zshrc
    printf "\033[32mSuccessful install\033[0m\n"
  else
    printf "\033[32mSkipping...\033[0m\n"
  fi
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Add config files
printf "Add config \033[33mdotfiles\033[0m? [\033[35my/n\033[0m] "
read dot
if [[ $dot == "y" || $dot == "Y" ]]; then
  printf "Create \033[33mhardlinks\033[0m? [\033[35my/n\033[0m] "
  read hard
  head -n 3 ./.gitignore > ~/.gitignore
  if [[ $hard == "y" || $hard == "Y" ]]; then
    ln ~/.gitconfig ./.gitconfig
    ln ~/.rtorrent.rc ./.rtorrent.rc
    ln ~/.tmux.conf ./.tmux.conf
    ln ~/.p10k.zsh ./.p10k.zsh
    ln ~/.zprofile ./.zprofile
    ln ~/.config/btop/btop.conf ./.config/btop/btop.conf
    ln ~/.config/neofetch/config.conf ./.config/neofetch/config.conf
    ln ~/.config/nvim/init.lua ./.config/nvim/init.lua
    ln ~/.config/nvim/lua/pandoks/init.lua ./.config/nvim/lua/pandoks/init.lua
    ln ~/.config/nvim/lua/pandoks/packer.lua ./.config/nvim/lua/pandoks/packer.lua
    ln ~/.config/nvim/lua/pandoks/remap.lua ./.config/nvim/lua/pandoks/remap.lua
    ln ~/.config/nvim/lua/pandoks/set.lua ./.config/nvim/lua/pandoks/set.lua
    ln ~/.config/nvim/after/plugin/completion/autoclosing.lua ./.config/nvim/after/plugin/completion/autoclosing.lua
    ln ~/.config/nvim/after/plugin/completion/cloak.lua ./.config/nvim/after/plugin/completion/cloak.lua
    ln ~/.config/nvim/after/plugin/completion/cmp.lua ./.config/nvim/after/plugin/completion/cmp.lua
    ln ~/.config/nvim/after/plugin/completion/colorpicker.lua ./.config/nvim/after/plugin/completion/colorpicker.lua
    ln ~/.config/nvim/after/plugin/completion/indent.lua ./.config/nvim/after/plugin/completion/indent.lua
    ln ~/.config/nvim/after/plugin/completion/null_ls.lua ./.config/nvim/after/plugin/completion/null_ls.lua
    ln ~/.config/nvim/after/plugin/completion/treesitter.lua ./.config/nvim/after/plugin/completion/treesitter.lua
    ln ~/.config/nvim/after/plugin/lsp/copilot.lua ./.config/nvim/after/plugin/lsp/copilot.lua
    ln ~/.config/nvim/after/plugin/lsp/dap.lua ./.config/nvim/after/plugin/lsp/dap.lua
    ln ~/.config/nvim/after/plugin/lsp/lspconfig.lua ./.config/nvim/after/plugin/lsp/lspconfig.lua
    ln ~/.config/nvim/after/plugin/lsp/lspsaga.lua ./.config/nvim/after/plugin/lsp/lspsaga.lua
    ln ~/.config/nvim/after/plugin/lsp/mason.lua ./.config/nvim/after/plugin/lsp/mason.lua
    ln ~/.config/nvim/after/plugin/navigation/bufferline.lua ./.config/nvim/after/plugin/navigation/bufferline.lua
    ln ~/.config/nvim/after/plugin/navigation/harpoon.lua ./.config/nvim/after/plugin/navigation/harpoon.lua
    ln ~/.config/nvim/after/plugin/navigation/telescope.lua ./.config/nvim/after/plugin/navigation/telescope.lua
    ln ~/.config/nvim/after/plugin/organization/filetree.lua ./.config/nvim/after/plugin/organization/filetree.lua
    ln ~/.config/nvim/after/plugin/organization/fugitive.lua ./.config/nvim/after/plugin/organization/fugitive.lua
    ln ~/.config/nvim/after/plugin/organization/git.lua ./.config/nvim/after/plugin/organization/git.lua
    ln ~/.config/nvim/after/plugin/organization/refactor.lua ./.config/nvim/after/plugin/organization/refactor.lua
    ln ~/.config/nvim/after/plugin/organization/undotree.lua ./.config/nvim/after/plugin/organization/undotree.lua
    ln ~/.config/nvim/after/plugin/running/term.lua ./.config/nvim/after/plugin/running/term.lua
    ln ~/.config/nvim/after/plugin/running/test.lua ./.config/nvim/after/plugin/running/test.lua
    ln ~/.config/nvim/after/plugin/running/trouble.lua ./.config/nvim/after/plugin/running/trouble.lua
    ln ~/.config/nvim/after/plugin/theme/color.lua ./.config/nvim/after/plugin/theme/color.lua
    ln ~/.config/nvim/after/plugin/theme/lualine.lua ./.config/nvim/after/plugin/theme/lualine.lua
    ln ~/.config/nvim/after/plugin/theme/winbar.lua ./.config/nvim/after/plugin/theme/winbar.lua
    ln ~/.config/nvim/after/plugin/theme/zen.lua ./.config/nvim/after/plugin/theme/zen.lua
    ln ~/.config/skhd/skhdrc ./.config/skhd/skhdrc
    ln ~/.config/skhd/template.md ./.config/skhd/template.md
    ln ~/.config/yabai/yabairc ./.config/yabai/yabairc
    ln ~/.config/yabai/template.md ./.config/yabai/template.md
  else
    cp ./.gitconfig ~/.gitconfig
    cp ./.rtorrent.rc ~/.rtorrent.rc
    cp ./.tmux.conf ~/.tmux.conf
    cp ./.p10k.zsh ~/.p10k.zsh
    cp ./.zshrc ~/.zshrc
    cp -R ./.config ~/.config
    cp -R ./.tmux ~/.tmux
    cp -R ./.hammerspoon ~/.hammerspoon
  fi
  printf "\033[32mSuccessful install\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi


# Install tmux plugins
tmux start-server
tmux new-session -d -s Installation>/dev/null 2>&1 
~/.tmux/plugins/tpm/bin/install_plugins

# Setup GitHub CLI
gh auth login
gh auth setup-git

# Setup rbenv
rbenv init

# Setup nvm
nvm install node
nvm use node
nvm install 18
nvm set-colors cgYmW

# Setup neovim
echo "If there are errors during the neovim installation, just spam :PackerSync [press any to continue]:"
read
nvim -c 'so' -c 'PackerSync' ~/.config/nvim/lua/pandoks/packer.lua

# Setup yabai
echo "Make sure you have csrutil disabled [press any to continue]:"
sudo nvram boot-args=-arm64e_preview_abi
yabai_string="$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"
echo "$yabai_string"| sudo tee /private/etc/sudoers.d/yabai > /dev/null

# Setup your .zshrc
echo "Set up your .zshrc [press any to continue]:"
read
nvim ~/.zshrc

# Setup your .hammerspoon
echo "Set up your .hammerspoon [press any to continue]:"
read
nvim ~/.hammerspoon/init.lua

# Restart computer
sudo shutdown -r now
