#!/bin/zsh

# Install Oh My Zsh
(sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended)
source .zshrc

# Install Homebrew and packages
echo "Make sure you are logged in to your Apple ID [press any to continue]:"
read
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
cp ./.zprofile ~/.zprofile
source .zprofile
brew bundle --file=./Brewfile
source .zshrc

# Add config files
head -n 3 ./.gitignore > ~/.gitignore
cp ./.gitconfig ~/.gitconfig
cp ./.rtorrent.rc ~/.rtorrent.rc
cp ./.tmux.conf ~/.tmux.conf
cp ./.p10k.zsh ~/.p10k.zsh
cp ./.zshrc ~/.zshrc
cp -R ./.config ~/.config
cp -R ./.tmux ~/.tmux
cp -R ./.hammerspoon ~/.hammerspoon

# Symlink for easier updates
echo "Do you want to hardlink files? [y/n]: "
read hardlink
if [[ $hardlink == "y" || $hardlink == "Y" ]]; then
  echo "Creating symlinks..."
  ln ~/.gitconfig ./.gitconfig
  ln ~/.rtorrent.rc ./.rtorrent.rc
  ln ~/.tmux.conf ./.tmux.conf
  ln ~/.p10k.zsh ./.p10k.zsh
  echo "Skipping .zshrc... due to it potentially having sensitive information"
  ln ~/.zprofile ./.zprofile
  # .config hard links
  ln ~/.config/btop/btop.conf ./.config/btop/btop.conf
  ln ~/.config/neofetch/config.conf ./.config/neofetch/config.conf
  ln ~/.config/nvim/init.lua ./.config/nvim/init.lua
  ln ~/.config/nvim/lua/pandoks/init.lua ./.config/nvim/lua/pandoks/init.lua
  ln ~/.config/nvim/lua/pandoks/packer.lua ./.config/nvim/lua/pandoks/packer.lua
  ln ~/.config/nvim/lua/pandoks/remap.lua ./.config/nvim/lua/pandoks/remap.lua
  ln ~/.config/nvim/lua/pandoks/set.lua ./.config/nvim/lua/pandoks/set.lua
  ln ~/.config/nvim/after/plugin/completion/autoclosing.lua ./.config/nvim/after/plugin/completion/autoclosing.lua
  ln ~/.config/nvim/after/plugin/completion/cloak.lua ./.config/nvim/after/plugin/completion/cloak.lua
  ln ~/.config/nvim/after/plugin/completion/cmp.lua ./.config/nvim/after/plugin/completion/cmp.lua
  ln ~/.config/nvim/after/plugin/completion/colorpicker.lua ./.config/nvim/after/plugin/completion/colorpicker.lua
  ln ~/.config/nvim/after/plugin/completion/indent.lua ./.config/nvim/after/plugin/completion/indent.lua
  ln ~/.config/nvim/after/plugin/completion/null_ls.lua ./.config/nvim/after/plugin/completion/null_ls.lua
  ln ~/.config/nvim/after/plugin/completion/treesitter.lua ./.config/nvim/after/plugin/completion/treesitter.lua
  ln ~/.config/nvim/after/plugin/lsp/copilot.lua ./.config/nvim/after/plugin/lsp/copilot.lua
  ln ~/.config/nvim/after/plugin/lsp/dap.lua ./.config/nvim/after/plugin/lsp/dap.lua
  ln ~/.config/nvim/after/plugin/lsp/lspconfig.lua ./.config/nvim/after/plugin/lsp/lspconfig.lua
  ln ~/.config/nvim/after/plugin/lsp/lspsaga.lua ./.config/nvim/after/plugin/lsp/lspsaga.lua
  ln ~/.config/nvim/after/plugin/lsp/mason.lua ./.config/nvim/after/plugin/lsp/mason.lua
  ln ~/.config/nvim/after/plugin/navigation/bufferline.lua ./.config/nvim/after/plugin/navigation/bufferline.lua
  ln ~/.config/nvim/after/plugin/navigation/harpoon.lua ./.config/nvim/after/plugin/navigation/harpoon.lua
  ln ~/.config/nvim/after/plugin/navigation/telescope.lua ./.config/nvim/after/plugin/navigation/telescope.lua
  ln ~/.config/nvim/after/plugin/organization/filetree.lua ./.config/nvim/after/plugin/organization/filetree.lua
  ln ~/.config/nvim/after/plugin/organization/fugitive.lua ./.config/nvim/after/plugin/organization/fugitive.lua
  ln ~/.config/nvim/after/plugin/organization/git.lua ./.config/nvim/after/plugin/organization/git.lua
  ln ~/.config/nvim/after/plugin/organization/refactor.lua ./.config/nvim/after/plugin/organization/refactor.lua
  ln ~/.config/nvim/after/plugin/organization/undotree.lua ./.config/nvim/after/plugin/organization/undotree.lua
  ln ~/.config/nvim/after/plugin/running/term.lua ./.config/nvim/after/plugin/running/term.lua
  ln ~/.config/nvim/after/plugin/running/test.lua ./.config/nvim/after/plugin/running/test.lua
  ln ~/.config/nvim/after/plugin/running/trouble.lua ./.config/nvim/after/plugin/running/trouble.lua
  ln ~/.config/nvim/after/plugin/theme/color.lua ./.config/nvim/after/plugin/theme/color.lua
  ln ~/.config/nvim/after/plugin/theme/lualine.lua ./.config/nvim/after/plugin/theme/lualine.lua
  ln ~/.config/nvim/after/plugin/theme/winbar.lua ./.config/nvim/after/plugin/theme/winbar.lua
  ln ~/.config/nvim/after/plugin/theme/zen.lua ./.config/nvim/after/plugin/theme/zen.lua
  ln ~/.config/skhd/skhdrc ./.config/skhd/skhdrc
  ln ~/.config/skhd/template.md ./.config/skhd/template.md
  ln ~/.config/yabai/yabairc ./.config/yabai/yabairc
  ln ~/.config/yabai/template.md ./.config/yabai/template.md
  echo "Skipping .hammerspoon... due to it potentially having sensitive information"
  echo "Finished linking"
fi

# Install tmux plugins
tmux start-server
tmux new-session -d -s Installation>/dev/null 2>&1 
~/.tmux/plugins/tpm/bin/install_plugins

# Setup GitHub CLI
gh auth login

# Setup rbenv
rbenv init

# Setup nvm
nvm install node
nvm use node
nvm install 18
nvm set-colors cgYmW

# Setup neovim
echo "If there are errors during the neovim installation, just spam :PackerSync [press any to continue]:"
read
nvim -c 'so' -c 'PackerSync' ~/.config/nvim/lua/pandoks/packer.lua

# Setup yabai
echo "Make sure you have csrutil disabled [press any to continue]:"
sudo nvram boot-args=-arm64e_preview_abi
yabai_string="$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"
echo "$yabai_string"| sudo tee /private/etc/sudoers.d/yabai > /dev/null

# Setup your .zshrc
echo "Set up your .zshrc [press any to continue]:"
read
nvim ~/.zshrc

# Setup your .hammerspoon
echo "Set up your .hammerspoon [press any to continue]:"
read
nvim ~/.hammerspoon/init.lua

# Restart computer
sudo shutdown -r now
