#!/bin/sh

# Installation introduction
printf '\033[36m
██████╗  █████╗ ███╗   ██╗██████╗  ██████╗ ██╗  ██╗███████╗
██╔══██╗██╔══██╗████╗  ██║██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝
██████╔╝███████║██╔██╗ ██║██║  ██║██║   ██║█████╔╝ ███████╗
██╔═══╝ ██╔══██║██║╚██╗██║██║  ██║██║   ██║██╔═██╗ ╚════██║
██║     ██║  ██║██║ ╚████║██████╔╝╚██████╔╝██║  ██╗███████║
╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝

   ██████╗  ██████╗ ████████╗███████╗██╗██╗     ███████╗███████╗
   ██╔══██╗██╔═══██╗╚══██╔══╝██╔════╝██║██║     ██╔════╝██╔════╝
   ██║  ██║██║   ██║   ██║   █████╗  ██║██║     █████╗  ███████╗
   ██║  ██║██║   ██║   ██║   ██╔══╝  ██║██║     ██╔══╝  ╚════██║
██╗██████╔╝╚██████╔╝   ██║   ██║     ██║███████╗███████╗███████║
╚═╝╚═════╝  ╚═════╝    ╚═╝   ╚═╝     ╚═╝╚══════╝╚══════╝╚══════╝\033[0m
[\033[35mpress any to continue\033[0m]'
read

# Install Oh My Zsh
printf "Install \033[33mOh My Zsh\033[0m? [\033[35my/n\033[0m] "
read omz
if [[ $omz == "y" || $omz == "Y" ]]; then
  (sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended)
  source ~/.zshrc
  printf "\033[32mSuccessful install\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Install Homebrew and packages
printf "Install \033[33mHomebrew\033[0m? [\033[35my/n\033[0m] "
read brew
if [[ $brew == "y" || $brew == "Y" ]]; then
  printf "\033[31mWarning\033[0m: make sure you are logged in to your Apple ID [\033[35mpress any to continue\033[0m]"
  read
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  printf "\033[33mNote:\033[0m Having a warning in the installation is normal\n"
  printf "Are you on an ARM system? [\033[35my/n\033[0m] "
  read arm
  if [[ $arm == "y" || $arm == "Y" ]]; then
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>./.zprofile
    sed -i '' '4s|".*"|"/opt/homebrew/bin/yabai"|' ./.hammerspoon/yabai.lua
  else
    echo 'eval "$(/usr/local/bin/brew shellenv)"' >>./.zprofile
    sed -i '' '4s|".*"|"/usr/local/bin/yabai"|' ./.hammerspoon/yabai.lua
  fi
  cp ./.zprofile ~/.zprofile
  source ~/.zprofile
  printf "\033[32mSuccessful install\033[0m\n"
  printf "Install \033[33mBrewfile software packages\033[0m? [\033[35my/n\033[0m] "
  read packages
  if [[ $packages == "y" || $package == "Y" ]]; then
    brew bundle --file=./Brewfile
    source ~/.zprofile
    printf "\033[32mSuccessful install\033[0m\n"
  else
    printf "\033[32mSkipping...\033[0m\n"
  fi
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Add config files
printf "Add config \033[33mdotfiles\033[0m? [\033[35my/n\033[0m] "
read dot
if [[ $dot == "y" || $dot == "Y" ]]; then
  head -n 3 ./.gitignore >~/.gitignore
  cp ./.gitconfig ~/.gitconfig
  cp ./.rtorrent.rc ~/.rtorrent.rc
  cp ./.tmux.conf ~/.tmux.conf
  cp ./.p10k.zsh ~/.p10k.zsh
  cp ./.zshrc ~/.zshrc
  cp ./Brewfile ~/Brewfile
  cp -R ./.config ~
  cp -R ./.tmux ~
  cp -R ./.hammerspoon ~
  printf "\033[32mConfig dotfiles added successfully\033[0m\n"
  printf "Create \033[33mhardlinks\033[0m? [\033[35my/n\033[0m] "
  read hard
  if [[ $hard == "y" || $hard == "Y" ]]; then
    # ~/
    ln -f ~/.gitconfig ./.gitconfig
    ln -f ~/.rtorrent.rc ./.rtorrent.rc
    ln -f ~/.tmux.conf ./.tmux.conf
    ln -f ~/.p10k.zsh ./.p10k.zsh
    ln -f ~/.zprofile ./.zprofile
    ln -f ~/Brewfile ./Brewfile

    link_directory() {
      directory=$1
      link=$2
      shift 2

      find_command="find $directory -type f"
      for excluded_file in "$@"; do
        find_command+=" ! -name $excluded_file"
      done

      eval $find_command | sed "s|^$directory/||" | xargs -I {} ln -f $directory/{} $link/{}
    }

    # .config/
    link_directory ~/.config/btop ./.config/btop
    link_directory ~/.config/neofetch ./.config/neofetch
    link_directory ~/.config/nvim ./.config/nvim
    link_directory ~/.config/yabai ./.config/yabai

    # .hammerspoon/
    link_directory ~/.hammerspoon ./.hammerspoon
    printf "\033[33mNote:\033[0m .zshrc cannot be hardlinked due to the possibility of private information being leaked [\033[35mpress any to continue\033[0m]"
    read
  fi
  source ~/.zprofile
  printf "\033[32mSuccessful install\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Install tmux plugins
printf "Setup \033[33mtmux\033[0m? [\033[35my/n\033[0m] "
read tmux
if [[ $tmux == "y" || $tmux == "Y" ]]; then
  tmux source-file ~/.tmux.conf
  tmux start-server
  tmux new-session -d -s Installation >/dev/null 2>&1
  ~/.tmux/plugins/tpm/bin/install_plugins
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Setup GitHub CLI
printf "Setup \033[33mGitHub\033[0m? [\033[35my/n\033[0m] "
read gh
if [[ $gh == "y" || $gh == "Y" ]]; then
  gh auth login
  gh auth setup-git
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Setup rbenv
printf "Setup \033[33mrbenv\033[0m? [\033[35my/n\033[0m] "
read rbenv
if [[ $rbenv == "y" || $rbenv == "Y" ]]; then
  rbenv init
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Setup nvm
printf "Setup \033[33mnvm\033[0m? [\033[35my/n\033[0m] "
read nvm
if [[ $nvm == "y" || $nvm == "Y" ]]; then
  source ~/.zshrc
  nvm install node
  nvm use node
  nvm install 18
  nvm set-colors cgYmW
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Setup neovim
printf "Setup \033[33mneovim\033[0m? [\033[35my/n\033[0m] "
read neovim
if [[ $neovim == "y" || $neovim == "Y" ]]; then
  printf "\033[33mNote:\033[0m Type :qa to exit vim ;) [\033[35mpress any to continue\033[0m]"
  read
  nvim
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Setup yabai
printf "Setup \033[33mYabaiWM\033[0m? [\033[35my/n\033[0m] "
read yabai
if [[ $yabai == "y" || $yabai == "Y" ]]; then
  printf "\033[31mWarning\033[0m: make sure csrutil is disabled [\033[35mpress any to continue\033[0m]"
  sudo nvram boot-args=-arm64e_preview_abi
  yabai_string="$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa"
  echo "$yabai_string" | sudo tee /private/etc/sudoers.d/yabai >/dev/null
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Setup your .zshrc
printf "Setup \033[33m.zshrc\033[0m? [\033[35my/n\033[0m] "
read zshrc
if [[ $zshrc == "y" || $zshrc == "Y" ]]; then
  nvim ~/.zshrc
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

# Setup your .hammerspoon
printf "Setup \033[33mHammerspoon\033[0m? [\033[35my/n\033[0m] "
read hammerspoon
if [[ $hammerspoon == "y" || $hammerspoon == "Y" ]]; then
  nvim ~/.hammerspoon/shortcuts.lua
  printf "\033[32mSuccessful setup\033[0m\n"
else
  printf "\033[32mSkipping...\033[0m\n"
fi

printf "\033[32mSUCCESS!\033[0m\n"
