---@meta

---One entry from `yabai -m query --windows`
---@class YabaiWindow
---@field id integer
---@field pid integer
---@field app string
---@field title string
---@field scratchpad string
---@field frame { x: number, y: number, w: number, h: number }
---@field role string
---@field subrole string
---@field ["root-window"] boolean
---@field display integer
---@field space integer
---@field level integer
---@field ["sub-level"] integer
---@field layer string
---@field ["sub-layer"] string
---@field opacity number
---@field ["split-type"] string
---@field ["split-child"] string
---@field ["stack-index"] integer
---@field ["can-move"] boolean
---@field ["can-resize"] boolean
---@field ["has-focus"] boolean
---@field ["has-shadow"] boolean
---@field ["has-parent-zoom"] boolean
---@field ["has-fullscreen-zoom"] boolean
---@field ["has-ax-reference"] boolean
---@field ["is-native-fullscreen"] boolean
---@field ["is-visible"] boolean
---@field ["is-minimized"] boolean
---@field ["is-hidden"] boolean
---@field ["is-floating"] boolean
---@field ["is-sticky"] boolean
---@field ["is-grabbed"] boolean

---@class WindowProfile
---@field app string yabai app name
---@field match? string|fun(win: YabaiWindow): boolean exact title match; nil = any window of the app
---@field space? integer space to focus before spawning
---@field spawn string[] args for /usr/bin/open
