[bootstrap.brew.taps]

[bootstrap.packages]
"brew-cask:ghostty" = "latest"
"brew-cask:hammerspoon" = "latest"
"brew-cask:helium-browser" = "latest"
"brew-cask:docker-desktop" = "latest"
"brew-cask:font-hack-nerd-font" = "latest"

[dotfiles]
"~/.zprofile" = "../../.zprofile"
"~/.hammerspoon" = "../../.hammerspoon"
